# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: racing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'racing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cracing.proto\x12\x06racing\"\x1c\n\x0cResetRequest\x12\x0c\n\x04seed\x18\x01 \x01(\x05\"$\n\rResetResponse\x12\x13\n\x0bobservation\x18\x01 \x03(\x02\"\x1d\n\x0bStepRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x03(\x02\"J\n\x0cStepResponse\x12\x13\n\x0bobservation\x18\x01 \x03(\x02\x12\x12\n\nterminated\x18\x03 \x01(\x08\x12\x11\n\ttruncated\x18\x04 \x01(\x08\x32x\n\rRacingService\x12\x34\n\x05Reset\x12\x14.racing.ResetRequest\x1a\x15.racing.ResetResponse\x12\x31\n\x04Step\x12\x13.racing.StepRequest\x1a\x14.racing.StepResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'racing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESETREQUEST']._serialized_start=24
  _globals['_RESETREQUEST']._serialized_end=52
  _globals['_RESETRESPONSE']._serialized_start=54
  _globals['_RESETRESPONSE']._serialized_end=90
  _globals['_STEPREQUEST']._serialized_start=92
  _globals['_STEPREQUEST']._serialized_end=121
  _globals['_STEPRESPONSE']._serialized_start=123
  _globals['_STEPRESPONSE']._serialized_end=197
  _globals['_RACINGSERVICE']._serialized_start=199
  _globals['_RACINGSERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
